services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "8443:8443"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HOSTNAME=localhost
      - KC_HTTPS_PORT=8443
    depends_on:
      - db
    networks:
      - keycloaknet
    restart: unless-stopped

  db:
    image: docker.io/library/postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - keycloaknet
    restart: unless-stopped

networks:
  keycloaknet:

